spring.application.name=dev
server.port=8080

#MongoDB API config
# Remote MongoDB connection

#Google OAuth2 login config
spring.security.oauth2.client.registration.google.client-id=947175545636-upkmn8khb5eg6aak14522gbrd7d6htuf.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email.profile
