spring.application.name=dev
server.port=8080

#MongoDB API config
# Remote MongoDB connection

#Google OAuth2 login config
spring.security.oauth2.client.registration.google.client-id=1090022950012-lftms8nu7qf33nqi9bcsg5pa384m4aek.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google
spring.security.oauth2.client.registration.google.scope=email.profile
